### ISSUE TITLE
Question: Logic behind INV_ALPHABETS

### ISSUE THREAD

**Issue by sr-gi** [andreasots/base32#23]
Hi there,

I'm trying to figure out the logic behind the INV_ALPHABETS to implement zbase32 based on your implementation of base32.

I don't quite understand why they are 43 elements long, nor why some values are repeated. Would you mind shedding some light on how you designed it?

PS: Apologies if this is not the best way to reach out, I did't find any other.

**Comment by sr-gi** [comment]
From

```
const RFC4648_INV_ALPHABET: [i8; 43] = [
    -1, -1, 26, 27, 28, 29, 30, 31, -1, -1, -1, -1, -1, 0, -1, -1, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8,
    9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
];
```

I've been able to get that:

```
[
    -1, -1, 26, 27, 28, 29, 30, 31, -1, -1,  --> Numbers (0-9)
    -1, -1, -1, 0, -1, -1, -1,   -->  ???
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,  --> Letters (A-Z)
];
```

However, I have no clue about the 7 elements in the middle.

**Comment by andreasots** [comment]
The `INV_ALPHABET`s map from ASCII characters to the Base32 digits. Since characters below `'0'` are not used the tables start at `'0'` and go to `'Z'`, in total 43 characters. `-1` in the table is a sentinel value signifying that that character is invalid in that Base32 variant. Some values are repeated because multiple characters can mean the same digit. The seven characters in the middle are in order `':'`, `';'`, `'<'`, `'='`, `'>'`, `'?'`, `'@'`. The fact that `'='` maps to a `0` is possibly a mistake.

**Comment by sr-gi** [comment]
Ohh, got it, those 7 characters are in between 0-9 and A-Z in ASCII.
